<?php

require_once '../lib/AsyncRunner.php';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $path = '../async_scripts/test_db_100_create_scritps';

    // Explicitly listing all scripts from script1.php to script100.php
    $scripts = [
        "$path/script1.php", 
        "$path/script2.php", 
        "$path/script3.php", 
        "$path/script4.php", 
        "$path/script5.php", 
        "$path/script6.php", 
        "$path/script7.php", 
        "$path/script8.php", 
        "$path/script9.php", 
        "$path/script10.php", 
        "$path/script11.php", 
        "$path/script12.php", 
        "$path/script13.php", 
        "$path/script14.php", 
        "$path/script15.php", 
        "$path/script16.php", 
        "$path/script17.php", 
        "$path/script18.php", 
        "$path/script19.php", 
        "$path/script20.php", 
        "$path/script21.php", 
        "$path/script22.php", 
        "$path/script23.php", 
        "$path/script24.php", 
        "$path/script25.php", 
        "$path/script26.php", 
        "$path/script27.php", 
        "$path/script28.php", 
        "$path/script29.php", 
        "$path/script30.php", 
        "$path/script31.php", 
        "$path/script32.php", 
        "$path/script33.php", 
        "$path/script34.php", 
        "$path/script35.php", 
        "$path/script36.php", 
        "$path/script37.php", 
        "$path/script38.php", 
        "$path/script39.php", 
        "$path/script40.php", 
        "$path/script41.php", 
        "$path/script42.php", 
        "$path/script43.php", 
        "$path/script44.php", 
        "$path/script45.php", 
        "$path/script46.php", 
        "$path/script47.php", 
        "$path/script48.php", 
        "$path/script49.php", 
        "$path/script50.php", 
        "$path/script51.php", 
        "$path/script52.php", 
        "$path/script53.php", 
        "$path/script54.php", 
        "$path/script55.php", 
        "$path/script56.php", 
        "$path/script57.php", 
        "$path/script58.php", 
        "$path/script59.php", 
        "$path/script60.php", 
        "$path/script61.php", 
        "$path/script62.php", 
        "$path/script63.php", 
        "$path/script64.php", 
        "$path/script65.php", 
        "$path/script66.php", 
        "$path/script67.php", 
        "$path/script68.php", 
        "$path/script69.php", 
        "$path/script70.php", 
        "$path/script71.php", 
        "$path/script72.php", 
        "$path/script73.php", 
        "$path/script74.php", 
        "$path/script75.php", 
        "$path/script76.php", 
        "$path/script77.php", 
        "$path/script78.php", 
        "$path/script79.php", 
        "$path/script80.php", 
        "$path/script81.php", 
        "$path/script82.php", 
        "$path/script83.php", 
        "$path/script84.php", 
        "$path/script85.php", 
        "$path/script86.php", 
        "$path/script87.php", 
        "$path/script88.php", 
        "$path/script89.php", 
        "$path/script90.php", 
        "$path/script91.php", 
        "$path/script92.php", 
        "$path/script93.php", 
        "$path/script94.php", 
        "$path/script95.php", 
        "$path/script96.php", 
        "$path/script97.php", 
        "$path/script98.php", 
        "$path/script99.php", 
        "$path/script100.php"
    ];

    $outputs = runScriptsAsync($scripts); // Call the function directly

    foreach ($outputs as $output) {
        echo "<pre>$output</pre>";
    }
}

echo "Script executed successfully.";

?>

