services:
  mongo:
    image: mongo
    container_name: my-mongo-container
    restart: always
    networks:
      - my-network

  mongo-express:
    image: mongo-express
    container_name: my-mongo-express-container
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    networks:
      - my-network

networks:
  my-network:


