# Use an official Node.js runtime as the base image
FROM node:14-alpine

# Set the working directory inside the container
WORKDIR /MY-PROJECT

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the entire project directory to the container
COPY . .

# Build the Vue.js app
RUN npm run build

# Expose the port on which the app will run (default is 8080)
EXPOSE 8080

# Start the app
CMD ["npm", "run", "serve"]
